### ISSUE TITLE
2 enhancements

### ISSUE THREAD

**Issue by miniop** [pannal/Sub-Zero#27]
Thank you very much its working perfect !!
I have some enhancements to ask : 

Is it possible to add more languages not only 3 ?

Is it possible to add an option scan to check which subtitles you have already and download only the rest ? (because now there is an option Scan: include external subtitles (skip if existing)  if it finds that you have an subtitles it will not download the rest of the chosen languages)

Thanks

**Comment by pannal** [comment]
Can you provide a log for the second question? It should not do that.

**Comment by pannal** [comment]
Add more languages: Yeah, I'm considering a dynamic field for that, where you can specify as many languages you can think of.

**Comment by miniop** [comment]
About the dynamic field will be great !

About the other i make a mistake it is wokring perfect. If it has already the language sub it doesnt skip the rest.

Thanks
