### ISSUE TITLE
Add basic information to the bundle (enable the i-icon in the agent list)

### ISSUE THREAD

**Issue by pannal** [pannal/Sub-Zero#28]

**Comment by pannal** [comment]
See https://github.com/ZeroQI/Hama.bundle/blob/master/Hama.bundle/Contents/Info.plist

**Comment by Roelie** [comment]
Can you explain this Enhancement?

**Comment by pannal** [comment]
Sure. If you take a look at your agent list, you'll notice that some plugins have a small "i"-icon which displays information about the plugin, and its logo.
I especially want that for Subliminal.bundle for quick links to the Plex thread aswell as to here. Also displaying the build version will come very handy.
