### ISSUE TITLE
Another error for Addicted provider in the patch_providers

### ISSUE THREAD

**Issue by chabou-san** [pannal/Sub-Zero#31]
I've been having this issue when I already was using RC-1, but I'm still having it in the RC-4 : 

```2015-10-12 08:34:32,502 (700002935000) :  INFO (logger:29) - subliminal_patch.patch_providers.addic7ed: Getting the page of show id 30, season 12
2015-10-12 08:34:32,630 (700002935000) :  DEBUG (logger:21) - requests.packages.urllib3.connectionpool: "GET /show/30?season=12 HTTP/1.1" 200 None
2015-10-12 08:34:33,521 (700002935000) :  ERROR (logger:29) - subliminal_patch.patch_provider_pool: Unexpected error in provider 'addic7ed', discarding it, because of: Traceback (most recent call last):
  File "/Users/itv/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/patch_provider_pool.py", line 176, in list_subtitles
    provider_subtitles = self[name].list_subtitles(video, provider_languages)
  File "/Users/itv/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal/providers/addic7ed.py", line 256, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.year)
  File "/Users/itv/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/patch_providers/addic7ed.py", line 107, in query
    series = match.group('series')
AttributeError: 'NoneType' object has no attribute 'group'```

I've tried to post the entire log file, but Github went wrong so I'm just posting the error part of the log.
I've tried with random user agent on and off, but it doesn't change anything.
I'm not sure what info you may need to tackle this issue, but I'll be glad to provide you more context if you need to.

**Comment by pannal** [comment]
I know that one. That happened to me before, when I was hammering addic7ed after a library refresh.
How many series are you refreshing when this happens? Can you post more context to something like pastebin?

**Comment by chabou-san** [comment]
I'm not home right now so I can't post you the whole log to pastebin: I'll do it later.
To explain how it happened, and it always do on the same episodes, I was refreshing the episodes #1 and #3 of Grey's Anatomy Season 12, both individually, and one at a time because I know the french subtitles I'm using are available on addic7ed. Interestingly enough, I manage to have the english subtitles downloaded, but I haven't checked if they come from another provider or from addic7ed (I'm using all providers).The episode #3 happens to have 2 video files. But the episode #1 doesn't, so it probably is not a key point of interest.
Not sure if all of this is relevant, but since I don't feel like I'm hammering addic7ed, I try to be as precise as I can before I can post the log.

**Comment by pannal** [comment]
This is most likely a punctuation issue.

**Comment by chabou-san** [comment]
Here's the pastebin : http://pastebin.com/2v5B3tbL

I also assumed it could be a punctuation issue due to the series name. But as you can see in the log, line 616, it's doing an http request ```GET /show/30?season=12 HTTP/1.1``` which matches the right show. So the issue might be somewhere else ?

Can you confirm that it's due to a punctuation issue, and if so what should I do to make it work ? Rename the show's folder, or the episode filenames ?

**Comment by pannal** [comment]
Please try the bleeding edge: https://github.com/pannal/Sub-Zero/archive/master.zip
Should work now.

**Comment by chabou-san** [comment]
Thanks for the reactivity ! I can confirm you the error is not present anymore and the subtitles are correctly downloaded. And I also thank you for your work. :)
