### ISSUE TITLE
pt-BR Brazilian Portuguese subtitles showing up as Unknown

### ISSUE THREAD

**Issue by chopeta** [pannal/Sub-Zero#32]
Is this something we can fix inside LocalMediaExtended?

Here's a nice forum thread that talks about the problem and even recommend an additional provider from Brazil (which by way would be nice to include as well)
* https://forums.plex.tv/discussion/109694/subtitles-shows-as-unknown

More discussions and complaints (I see them as potential users for Sub-Zero):
* https://forums.plex.tv/discussion/155313/unknown-srt-for-pob-srt-or-pb-srt
* https://forums.plex.tv/discussion/99535/why-do-my-subtitles-show-up-as-unknown
* https://forums.plex.tv/discussion/65901/what-is-the-code-for-brazilian-subtitle-language

I hope there's some hack we can to get this done otherwise no big deal :)

**Comment by pannal** [comment]
Actually showing pb as "Portuguese Brazilian" will not work as the internal language mapping of Plex seems to be fixed and only resolves to ISO 639-2, which doesn't know of pt-BR.

I guess I could make it show as "Portuguese" instead of Unknown.

**Comment by chopeta** [comment]
That would be close enough for me but I think it's a hack that could badly affect others so likely not a good a idea.

It could be a problem for some people that may want to have both languages (Portuguese and Brazilian Portuguese) listed. Right now these people see Portuguese and Unknown and after the proposed change they would both show as Portuguese.

For me, it's an error to use ISO 639 here instead of IETF - Brazilian Portuguese is supported by almost every subtitle database. Plex even support proper download of pt-BR subs but can't display it correctly. Doesn't make any sense.

Anyway, if there's nothing we can do in a proper way I guess we can cancel this one :(

**Comment by pannal** [comment]
I could make it optional: something like "Treat subsets of known languages as their parent, so they don't appear as Unknown".

What could also be done is to patch the language list of Plex from the outside - the very core is a pretty open Python implementation, I may look into that. That won't be possible from inside the SZ code, though, so one would have to patch PMS separately.

**Comment by chopeta** [comment]
Something optional "Treat subsets of known languages as their parent, so they don't appear as Unknown" sounds really good :)

Hacking/patch PMS code doesn't sound good for me :(

I've just ask the people from the threads to come and join the discussion. 

I hope they come and bring their opinion as well help us testing and provide feedback.

**Comment by pannal** [comment]
fixed in 1.1.0.1
