### ISSUE TITLE
Incorporate yify subtitles api for movies

### ISSUE THREAD

**Issue by ledge74** [pannal/Sub-Zero#47]
Hey panni, what do you think about adding yifysubtitles API for movies matching the YIFY release group?
I could not find a python library but this could help implementing it:
https://github.com/gtuk/yifysubs

The main reason using this subtitles provider could be interesting to add is that subtitles are 99.99% correct when concerning yify movies.

Also YIFY Subtitles API needs IMDB ID, I don't know if it is available within PMS

**Comment by chopeta** [comment]
Great idea!

**Comment by pannal** [comment]
I'm not very fond of this. Sure it will help with subtitles form that particular group, but then the plugin would be directly associated with illegal activity.

It would be pretty easy to implement, though.

**Comment by ledge74** [comment]
Mmhh. I get the dilemma you are facing with this. I'll say do as you think is best for the plugins, as the subtitles for YIFY release are often available on other subtitles providers websites.

**Comment by pannal** [comment]
Sorry :)

**Comment by chopeta** [comment]
Sounds like a reasonable explanation to me.
