### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by SunMar** [pannal/Sub-Zero#53]
Just noticed that the LICENSE file still only contains only Bram Walet for the copyright. If I'm not mistaken you are entitled the copyright to your modifications :). Something like:

Original work Copyright (c) 2014 Bram Walet
Modified work Copyright 2015 pannal

But IANAL, http://programmers.stackexchange.com/questions/157968/how-to-manage-a-copyright-notice-in-an-open-source-project

Thank you for the amazing work on this!

**Comment by pannal** [comment]
Thanks for the suggestion. With 1.3.0 I've changed the license to The Unlicense while keeping the original notice intact.
