### ISSUE TITLE
Support plex.tv account/authentication

### ISSUE THREAD

**Issue by chopeta** [pannal/Sub-Zero#54]
I believe this is required for users using Plex Home on their servers.

I don't know the best or proper way to implement but I've seen the way plexPy project does it and it looks pretty simple and easy to use.

User must enter his login and password info. for his plex.tv account and then PMS Token is automatically grabbed allowing proper communication between the plugin and the server without having to ask the user to provide complex token field.

Anyway, I am not saying this the way to go but here's the idea.

Code repo is here on github: https://github.com/drzoidberg33/plexpy

**Comment by pannal** [comment]
I guess it's done here: https://github.com/drzoidberg33/plexpy/blob/master/plexpy/plextv.py
I'd rather give the user the option to add his plex token than providing his credentials to some random subtitle agent...

**Comment by chopeta** [comment]
It's only necessary once. The token never changes.

And believe me, this is no random subtitle agent.... this is the sh** subtitle agent :) and it's open-source so no one would never doubt about entering their credentials because they know such data would never be used or saved in a wrong way and they can check the code if they want.

Thanks for considering adding this functionality.

**Comment by pannal** [comment]
Hopefully working in 1.3.0.232

**Comment by chopeta** [comment]
Hey @pannal , sorry I cound't test this early.

So far I only have 2 minor security issues:

1) My user password is beign written in the logs when saving prefs
2) After my plex account is validated my token is also displayed in the logs

Other than that it seems to be working great!

**Comment by pannal** [comment]
Where exactly is that so? The token part I get, because of my debug print, right? I can remove that in the next version, that was just for testing purposes.

The password shouldn't be written to the logs on save. If so, I probably can't do anything against it.

**Comment by cbjerg** [comment]
Mine did it too: 
DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.subzero/prefs/set?plex_username=cbjerg&plex_password=XXXXXXXXX

**Comment by eltismerino** [comment]
I don't think I can do anything to prevent that. You can turn off debug logging I guess.

**Comment by pannal** [comment]
I don't think I can do anything to prevent that. That's plex internal, the password field is set to "hidden" and "secure", just as any other password field in SZ. You can turn off debug logging.
