### ISSUE TITLE
Add last run info for periodic search

### ISSUE THREAD

**Issue by ledge74** [pannal/Sub-Zero#56]
Hey Panni,

One thing I have noticed in the 1.3.x beta is that there is no way to know when the periodic search was last triggered, expect if you go into the logs. Trakt.tv bundle has a cool way to show it and I thought it could be a great feature for the upcoming Sub-Zero releases:

![screen shot 2015-10-27 at 18 48 41](https://cloud.githubusercontent.com/assets/6603944/10767242/84248948-7cdb-11e5-9f2c-71e35dea3406.png)

Cheers

**Comment by chopeta** [comment]
+1

**Comment by pannal** [comment]
Fixed in 1.3.0.232
