### ISSUE TITLE
Donate buttons on the README and info page

### ISSUE THREAD

**Issue by chopeta** [pannal/Sub-Zero#57]
Please add a donate button in both the README.md file and the pluging info/about page so we can easily send you a beer.

For the README.md I guess you can use the same idea as https://github.com/drzoidberg33/plexpy 

For the plugin info/about page I don't know how to do, but I guess something similar should work as well.

**Comment by pannal** [comment]
README done (1.3.0), info page will come.

**Comment by eilandert** [comment]
already donated :+1:

**Comment by chopeta** [comment]
The default page for the github repo is the README.me from the master branch... shouldn't donate button be available in there as well? :)

**Comment by pannal** [comment]
Nah, I'm confident the README.md from the 1.3.0 branch will be in the master branch on the weekend :)
