### ISSUE TITLE
Display progress of "Search for missing subtitles" process

### ISSUE THREAD

**Issue by chopeta** [pannal/Sub-Zero#62]
Can we display "Search for missing subtitles" (automatic or manual) progress status and % in the channel page?

Something like the "Manual Sync" from the Trakt plugin.

It would be nice to know how long it's taking the execution so one can better tweak schedule parameters.

**Comment by pannal** [comment]
Would a summary of the last run help in the short term? Like "last run took: ..."

**Comment by pannal** [comment]
It's not that easy, though, I doubt it'll get into 1.3.0.

**Comment by pannal** [comment]
I just rewrote the tasks subsystem, because it lacked basic functionality. With that, also this ticket was solved :)
