### ISSUE TITLE
Issue in channel - movie title

### ISSUE THREAD

**Issue by miniop** [pannal/Sub-Zero#72]
In channel i saw one issue.
Some of my movies titles have Greek characters.
When i go to channel , Subtitles for on Deck the movie that has greek title is showing as empty.
Maybe you can use unicode to display the titles ?

**Comment by eltismerino** [comment]
I'd love to, but Plex seems to enforce ASCII there (in fact SZ is, because it was erroring out otherwise).
Do you know of other channels which manage to do this? I could have a look then.

**Comment by eltismerino** [comment]
I just had a look here: https://forums.plex.tv/discussion/144589/unicode-and-special-characters-in-directoryobjects-and-mediacontainers#latest

Will look into it a little further.

**Comment by eltismerino** [comment]
Please try the bleeding edge: https://github.com/pannal/Sub-Zero/archive/master.zip

**Comment by pannal** [comment]
Please try the bleeding edge: https://github.com/pannal/Sub-Zero/archive/master.zip

**Comment by miniop** [comment]
yes with this version the titles are displayed

**Comment by pannal** [comment]
Nice, closed.
